#!C:\Users\HP\AppData\Local\Programs\Python\Python38-32\python.exe
print("Content-type:text/html\r\n\r\n")
print('<!DOCTYPE html>')
print('<head>')
print('<title>Search</title>')
print('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">')
print('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">')

print('<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>')

print('<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>')

print('<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>')

print('</head>')
print('<style>')
print('.card-body{')
print('height: 400px;')
print('overflow: scroll;')
print('}')
print('@media screen and (max-width: 600px){')
print('background-color:white;')
print('}')
print('</style>')
print('<body>')
print('<header>')
print('<center class="mt-3 text-danger"><h1>Search Here</h1></center>')
print('</header>')
print('<div class="container">')
print('<div class="row mt-2">')
print('<div class="col-sm-8">')
print('<center><input type="search" placeholder="Search.." name="search" id="search" class="form-control">')
print('</div>')
print('<div class="col-sm-4">')
print('<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Search</button><center>')
print('</div>')
print('</div>')
print('</div>')

print('<div class="container mt-3">')
print('<div class="row">')
print('<div class="col-sm-4">')
print('<div class="card">')
print('<div class="card-header bg-success text-white">')
print('GOOGLE')
print('</div>')
print('<div class="card-body">')


print('</div>')
print('</div>')
print('</div>')
print('<div class="col-sm-4">')
print('<div class="card">')
print('<div class="card-header bg-primary text-white">')
print('YAHOO')
print('</div>')
print('<div class="card-body">')
        
print('</div>')
print('</div>')
print('</div>')
print('<div class="col-sm-4">')
print('<div class="card">')
print('<div class="card-header bg-dark text-white">')
print('BING')
print('</div>')
print('<div class="card-body">')
        
print('</div>')
print('</div>')
print('</div>')
  
print('</div>')
print('</div>')
print('</body>')
print('</html>')